// Explain flow (highlight / circle / confirm step / context / panel) against
// the unpacked extension.
//
//   npx playwright test --config=tests/explain.config.mjs
//
// A local Node server serves the test pages AND a mock /api/v1/explain,
// /api/v1/explain/context and /api/v1/reformat/reformat-document, and the
// extension's backendBaseUrl is pointed at it. The background service worker
// therefore makes real fetches to a server we control — no dependency on the
// real backend, and no SW request interception. Request bodies are recorded.
//
// *.synapse.test resolves to 127.0.0.1 (--host-resolver-rules) so a page can
// be served under a sensitive-looking hostname (mail.synapse.test).
import { expect, test } from '@playwright/test';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { launchExtension, readStorage, writeStorage } from './extension.mjs';

const FIXTURES = path.join(path.dirname(fileURLToPath(import.meta.url)), 'fixtures');
// Generated by tests/fixtures/make-pdf-fixtures.mjs (committed).
const SAMPLE_PDF = fs.readFileSync(path.join(FIXTURES, 'sample.pdf'));
const PROTECTED_PDF = fs.readFileSync(path.join(FIXTURES, 'protected.pdf'));

test.describe.configure({ mode: 'serial' });

let context;
let server;
let base;
let port;
let page;
let extensionId;
const requests = [];     // POST /explain bodies
const ctxUploads = [];   // POST /explain/context bodies
const docReads = [];     // POST /reformat/reformat-document bodies
const consoleErrors = [];
const explainQueue = []; // { status, body } replies for the next POST /explain calls, in order
let reexplainsServed = 0;
let ctxCounter = 0;

const ARTICLE = `<!doctype html><html><head><meta charset="utf-8"><title>Cells 101</title>
<meta name="description" content="A short primer on cells">
<style>body{font:18px/1.6 Georgia,serif;max-width:720px;margin:40px auto;padding:0 20px}
#chart{width:320px;height:180px;background:linear-gradient(90deg,#2b6cb0 0 30%,#38a169 30% 70%,#d69e2e 70%)}</style></head>
<body>
<nav><a href="/">Home</a> <a href="/x">Navigation link text</a></nav>
<main>
<h1 id="title">An introduction to cells</h1>
<p id="p1">Mitochondria are membrane-bound organelles that generate most of the chemical energy needed to power the cell's biochemical reactions.</p>
<p id="p2">Ribosomes read messenger RNA and assemble amino acids into proteins, following the genetic code one codon at a time.</p>
<div id="chart" role="img" aria-label="chart"></div>
<p id="p3">The cell membrane controls what enters and leaves the cell.</p>
<p><input id="field" value="type here"></p>
</main>
<div style="height:1600px"></div>
</body></html>`;

const SETTINGS_PAGE = `<!doctype html><html><head><meta charset="utf-8"><title>Settings - MoneyApp</title>
<meta property="og:site_name" content="MoneyApp"></head>
<body style="font:16px/1.5 sans-serif;margin:40px">
<main>
<h1>Settings</h1>
<section><h2>Profile</h2><p>Your name and photo.</p></section>
<section>
  <h2>Connected accounts</h2>
  <form id="acct">
    <h3>Chase Checking</h3>
    <p>Last synced 3 days ago. Transactions may be missing.</p>
    <label>Nickname <input name="nick" value="Main"></label>
    <label for="type">Account type</label> <select id="type"><option>Checking</option></select>
    <div role="toolbar" aria-label="Account actions">
      <button type="button" id="sync" title="Refresh transactions from your bank">Sync</button>
      <button type="button" id="rm">Remove</button>
    </div>
  </form>
</section>
</main>
</body></html>`;

const NOTES = 'Plain text notes.\nLine two of the notes about mitochondria and ribosomes.\nA third line to make the file longer.\n';

function json(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

function readBody(req) {
  return new Promise((resolve) => {
    let raw = '';
    req.on('data', (c) => { raw += c; });
    req.on('end', () => resolve(JSON.parse(raw || '{}')));
  });
}

function startServer() {
  return new Promise((resolve) => {
    const srv = http.createServer(async (req, res) => {
      const url = new URL(req.url, 'http://x');
      if (req.method === 'GET' && url.pathname === '/article.html') {
        res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
        return res.end(ARTICLE);
      }
      if (req.method === 'GET' && url.pathname === '/settings.html') {
        res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
        return res.end(SETTINGS_PAGE);
      }
      if (req.method === 'GET' && url.pathname === '/notes.txt') {
        res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
        return res.end(NOTES);
      }
      if (req.method === 'GET' && url.pathname === '/paper.pdf') {
        res.writeHead(200, { 'Content-Type': 'application/pdf' });
        return res.end(SAMPLE_PDF);
      }
      if (req.method === 'GET' && url.pathname === '/locked.pdf') {
        res.writeHead(200, { 'Content-Type': 'application/pdf' });
        return res.end(PROTECTED_PDF);
      }
      if (req.method === 'GET' && url.pathname === '/broken.pdf') {
        res.writeHead(200, { 'Content-Type': 'application/pdf' });
        return res.end('this is not a pdf at all');
      }
      if (req.method === 'POST' && url.pathname === '/api/v1/explain') {
        const body = await readBody(req);
        requests.push(body);
        const re = body.reexplain;
        if (re) reexplainsServed += 1;
        const reply = explainQueue.shift() || {
          status: 200,
          body: {
            html: re
              ? `<p>Mock ${re.mode} version for ${body.kind}</p>`
              : `<p>Mock explanation for ${body.kind}</p>`,
            kind: body.kind,
            model_used: 'mock',
            history_entry: null,
            usage: null,
            reexplain: re ? { free: true, free_remaining: Math.max(0, 10 - reexplainsServed), free_limit: 10 } : null,
          },
        };
        setTimeout(() => json(res, reply.status, reply.body), 150);
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/v1/explain/context') {
        const body = await readBody(req);
        ctxUploads.push(body);
        ctxCounter += 1;
        // PDFs arrive as base64; the real backend extracts their text.
        const chars = (body.document_text || '').length || (body.document_base64 ? 4321 : 0);
        return json(res, 200, { context_id: `ctx-${ctxCounter}`, chars, truncated: false, expires_in: 3600 });
      }
      if (req.method === 'POST' && url.pathname === '/api/v1/reformat/reformat-document') {
        docReads.push(await readBody(req));
        return json(res, 200, { html: '<h2>Notes rebuilt</h2><p id="rebuilt">Rebuilt paragraph about plain notes and organelles.</p>' });
      }
      json(res, 404, { detail: 'not found' });
    });
    srv.listen(0, '127.0.0.1', () => resolve(srv));
  });
}

function worker() {
  const [sw] = context.serviceWorkers();
  if (!sw) throw new Error('service worker not running');
  return sw;
}

async function waitForRequests(n) {
  await expect.poll(() => requests.length, { timeout: 15_000 }).toBeGreaterThanOrEqual(n);
  return requests[n - 1];
}

async function openArticle(origin = base) {
  await page.bringToFront();
  await page.goto(`${origin}/article.html`);
  await expect(page.locator('#synapse-fab')).toBeVisible();
  await expect(page.locator('#synapse-history-btn')).toBeAttached();
}

/** Traces a loop around a locator with the Alt+S chord. */
async function chordAround(locator, pad = 10) {
  const box = await locator.boundingBox();
  const pts = [
    [box.x - pad, box.y - pad], [box.x + box.width + pad, box.y - pad],
    [box.x + box.width + pad, box.y + box.height + pad], [box.x - pad, box.y + box.height + pad],
    [box.x - pad, box.y - pad + 2],
  ];
  await page.mouse.move(pts[0][0], pts[0][1]);
  await page.keyboard.down('Alt');
  await page.keyboard.down('KeyS');
  for (const [x, y] of pts.slice(1)) await page.mouse.move(x, y, { steps: 6 });
  await page.keyboard.up('KeyS');
  await page.keyboard.up('Alt');
}

/** FAB click-to-trace around a locator. */
async function fabAround(locator, pad = 8) {
  const box = await locator.boundingBox();
  await page.locator('#synapse-fab').click();
  await page.mouse.click(box.x - pad, box.y - pad);
  await page.mouse.move(box.x + box.width + pad, box.y - pad, { steps: 6 });
  await page.mouse.move(box.x + box.width + pad, box.y + box.height + pad, { steps: 6 });
  await page.mouse.move(box.x - pad, box.y + box.height + pad, { steps: 6 });
  await page.mouse.click(box.x - pad, box.y);
}

/** Selects an element's text programmatically and explains it via the bubble. */
async function selectAndExplain(selector) {
  await page.evaluate((sel) => {
    const el = document.querySelector(sel);
    const r = document.createRange();
    r.selectNodeContents(el);
    const s = window.getSelection();
    s.removeAllRanges();
    s.addRange(r);
    document.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
  }, selector);
  const bubble = page.locator('#synapse-bubble');
  await expect(bubble).toBeVisible();
  await bubble.click();
}

async function setContextSettings(value) {
  await writeStorage(worker(), { explainContextSettings: value });
}

test.beforeAll(async () => {
  server = await startServer();
  port = server.address().port;
  base = `http://127.0.0.1:${port}`;
  const launched = await launchExtension({ args: ['--host-resolver-rules=MAP *.synapse.test 127.0.0.1'] });
  context = launched.context;
  extensionId = launched.extensionId;
  await writeStorage(launched.worker, {
    onboardingComplete: true,
    providerConfig: { backendBaseUrl: base, useBackendProxy: true, tier: 'free' },
  });
  for (const p of context.pages()) {
    if (p.url().includes('onboarding.html')) await p.close();
  }
  // The install-time onboarding tab can also open after this point and steal
  // focus (a blurred window cancels circle mode), so close it whenever it appears.
  context.on('page', async (p) => {
    try { await p.waitForLoadState('domcontentloaded'); } catch (_) { return; }
    if (p.url().includes('onboarding.html')) {
      await p.close().catch(() => {});
      await page?.bringToFront().catch(() => {});
    }
  });
  page = context.pages()[0] || (await context.newPage());
  page.on('console', (m) => { if (m.type() === 'error') consoleErrors.push(m.text()); });
  page.on('pageerror', (e) => consoleErrors.push(String(e)));
});

test.afterAll(async () => {
  await context?.close();
  await new Promise((r) => server?.close(r));
});

test('Article mode entry points are hidden; FAB is present', async () => {
  await openArticle();
  await expect(page.locator('#synapse-panel')).toHaveCount(0);
  await expect(page.locator('#sp-main-btn')).toHaveCount(0);
  await expect(page.locator('#sp-focus-btn')).toHaveCount(0);
});

test('selecting text shows the bubble; clicking it explains with page context and paints green', async () => {
  await openArticle();
  await page.locator('#p1').click({ clickCount: 3 });
  const bubble = page.locator('#synapse-bubble');
  await expect(bubble).toBeVisible();

  await bubble.click();
  const panel = page.locator('#synapse-explain-panel');
  await expect(panel).toHaveClass(/s-visible/);

  const req = await waitForRequests(1);
  expect(req.kind).toBe('text');
  expect(req.text).toContain('Mitochondria are membrane-bound organelles');
  expect(req.image_base64).toBeNull();
  expect(req.anchor.quote).toContain('Mitochondria are membrane-bound organelles');
  expect(req.page_url).toBe(`${base}/article.html`);
  expect(req.source).toBe('page');
  expect(req.fingerprint).toMatch(/^ext-/);

  // Local context: heading path and surrounding text.
  expect(req.context.local.heading_path).toEqual(['An introduction to cells']);
  expect(req.context.local.surrounding_text).toContain('Mitochondria');
  expect(req.context.local.element).toBeUndefined();
  // Page context on a normal site: title, description, outline, main text without the nav.
  expect(req.context.page.title).toBe('Cells 101');
  expect(req.context.page.site_name).toBe('127.0.0.1');
  expect(req.context.page.description).toBe('A short primer on cells');
  expect(req.context.page.outline).toEqual(['An introduction to cells']);
  expect(req.context.page.main_text).toContain('Ribosomes read messenger RNA');
  expect(req.context.page.main_text).not.toContain('Navigation link text');
  expect(req.context_id).toBeNull();

  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for text');
  await expect(panel.locator('.sxp-ctx-used')).toContainText('page context');
  await expect(panel.locator('.sxp-item')).toHaveCount(1);

  // Painted with the Custom Highlight API (the registry is per document).
  await expect.poll(() => page.evaluate(() => CSS.highlights.has('synapse-explained'))).toBe(true);

  // Saved locally by the background (free/anonymous history).
  const stored = await readStorage(worker(), 'explainHistoryLocal');
  expect(stored.explainHistoryLocal).toHaveLength(1);
  expect(stored.explainHistoryLocal[0].hostname).toBe('127.0.0.1');
  expect(stored.explainHistoryLocal[0].result_html).toContain('Mock explanation');
});

test('selection inside an input does not show the bubble', async () => {
  await openArticle();
  await page.locator('#field').click({ clickCount: 3 });
  await page.waitForTimeout(400);
  await expect(page.locator('#synapse-bubble')).toHaveCount(0);
});

test('after reload: history button shows, highlight restored, click reopens without an API call', async () => {
  await openArticle();
  const historyBtn = page.locator('#synapse-history-btn');
  await expect(historyBtn).toHaveClass(/s-has-history/);
  await expect(historyBtn.locator('.sxh-count')).toHaveText('1');
  await expect.poll(() => page.evaluate(() => CSS.highlights.get('synapse-explained')?.size ?? 0)).toBe(1);

  const before = requests.length;
  const box = await page.locator('#p1').boundingBox();
  await page.mouse.click(box.x + 40, box.y + 12);
  const panel = page.locator('#synapse-explain-panel');
  await expect(panel).toHaveClass(/s-visible/);
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for text');
  await page.waitForTimeout(300);
  expect(requests.length).toBe(before);

  // Escape inside the panel closes it.
  await panel.locator('.sxp-close').focus();
  await page.keyboard.press('Escape');
  await expect(panel).not.toHaveClass(/s-visible/);

  // History button opens the panel without starting circle mode.
  await historyBtn.click();
  await expect(panel).toHaveClass(/s-visible/);
  await expect(page.locator('#synapse-circle-overlay')).toHaveCount(0);
});

test('FAB click enters circle mode; Escape cancels', async () => {
  await openArticle();
  await page.locator('#synapse-fab').click();
  await expect(page.locator('#synapse-circle-overlay')).toBeAttached();
  await expect(page.locator('#synapse-circle-tip')).toContainText('Click where you want to start');
  await page.keyboard.press('Escape');
  await expect(page.locator('#synapse-circle-overlay')).toHaveCount(0);
});

test('Alt+S chord: a tiny trace shows the gentle message and sends nothing', async () => {
  await openArticle();
  const before = requests.length;
  await page.mouse.move(300, 300);
  await page.keyboard.down('Alt');
  await page.keyboard.down('KeyS');
  await expect(page.locator('#synapse-circle-overlay')).toBeAttached();
  await page.mouse.move(305, 302, { steps: 3 });
  await page.keyboard.up('KeyS');
  await page.keyboard.up('Alt');
  await expect(page.locator('#synapse-circle-overlay')).toHaveCount(0);
  await expect(page.locator('#synapse-circle-tip')).toContainText('too small');
  await page.waitForTimeout(300);
  expect(requests.length).toBe(before);
  await expect(page.locator('#synapse-confirm-bar')).toHaveCount(0);
});

test('circle shows the confirm bar with a preview; Enter sends exactly one request with the masked crop', async () => {
  await openArticle();
  const before = requests.length;
  await chordAround(page.locator('#p2'));

  const bar = page.locator('#synapse-confirm-bar');
  await expect(bar).toBeVisible();
  await expect(bar).toHaveAttribute('role', 'dialog');
  await expect(page.locator('#synapse-circle-outline')).toBeAttached();
  const img = bar.locator('.sxc-preview img');
  await expect(img).toHaveAttribute('src', /^data:image\/(webp|jpeg);base64,/);
  await expect(bar.getByRole('button', { name: /Confirm/ })).toBeFocused();
  await expect(bar.locator('[role="status"]')).toContainText('Press Enter');
  // Synapse UI is restored after the capture, and nothing was sent yet.
  await expect.poll(() => page.evaluate(() => document.documentElement.classList.contains('synapse-capture-hide'))).toBe(false);
  await page.waitForTimeout(400);
  expect(requests.length).toBe(before);
  const previewSrc = await img.getAttribute('src');

  await page.keyboard.press('Enter');
  const req = await waitForRequests(before + 1);
  await expect(bar).toHaveCount(0);
  await expect(page.locator('#synapse-circle-outline')).toHaveCount(0);
  expect(req.kind).toBe('image');
  expect(req.image_base64.length).toBeGreaterThan(100);
  expect(['image/webp', 'image/jpeg']).toContain(req.image_media_type);
  expect(req.thumbnail_base64).toBeTruthy();
  const thumb = Buffer.from(req.thumbnail_base64, 'base64');
  expect(thumb.subarray(0, 4).toString('latin1')).toBe('RIFF');
  expect(thumb.subarray(8, 12).toString('latin1')).toBe('WEBP');
  expect(thumb.length).toBeLessThanOrEqual(200 * 1024);
  // The preview was exactly the crop that was sent (no second screenshot).
  expect(previewSrc).toBe(`data:${req.image_media_type};base64,${req.image_base64}`);
  expect(req.text).toContain('Ribosomes read messenger RNA');
  expect(req.text).not.toContain('Mitochondria');
  expect(req.anchor.rect.width).toBeGreaterThan(50);
  expect(req.anchor.quote).toContain('Ribosomes');
  expect(req.context.local.heading_path).toEqual(['An introduction to cells']);
  expect(req.context.local.surrounding_text).toContain('Ribosomes');
  expect(req.context.page.main_text).toContain('Ribosomes');

  const panel = page.locator('#synapse-explain-panel');
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for image');
  await page.waitForTimeout(500);
  expect(requests.length).toBe(before + 1); // exactly one
  // The source is emphasised.
  await expect(page.locator('.synapse-emphasis')).toHaveCount(1);
});

/** Pending confirm-step captures in chrome.storage.session (the source of truth). */
async function storedCaptureKeys() {
  return worker().evaluate(async () => Object.keys(await chrome.storage.session.get(null)).filter((k) => k.startsWith('pendingCapture:')));
}

/** Stops the extension's MV3 service worker the way Chrome does when it is idle. */
async function stopServiceWorker() {
  const ext = await context.newPage();
  await ext.goto(`chrome-extension://${extensionId}/viewer/viewer.html`);
  const cdp = await context.newCDPSession(ext);
  const statuses = [];
  cdp.on('ServiceWorker.workerVersionUpdated', (e) => {
    for (const v of e.versions) if (v.scriptURL.endsWith('/background.js')) statuses.push(v.runningStatus);
  });
  await cdp.send('ServiceWorker.enable');
  await cdp.send('ServiceWorker.stopAllWorkers');
  await expect.poll(() => statuses[statuses.length - 1], { timeout: 10_000 }).toBe('stopped');
  await cdp.detach();
  await ext.close();
}

test('confirm step survives the service worker being suspended (crop kept in storage.session)', async () => {
  await openArticle();
  const before = requests.length;
  await chordAround(page.locator('#p2'));
  const bar = page.locator('#synapse-confirm-bar');
  await expect(bar).toBeVisible();
  const previewSrc = await bar.locator('.sxc-preview img').getAttribute('src');
  expect(await storedCaptureKeys()).toHaveLength(1);

  // Chrome suspends idle MV3 workers after ~30 s; the in-memory map dies with it.
  await stopServiceWorker();

  await page.keyboard.press('Enter');
  const req = await waitForRequests(before + 1);
  expect(req.kind).toBe('image');
  expect(previewSrc).toBe(`data:${req.image_media_type};base64,${req.image_base64}`);
  expect(req.thumbnail_base64).toBeTruthy();
  await expect(page.locator('#synapse-explain-panel .sxp-result')).toContainText('Mock explanation for image');
  // Taken once, then deleted.
  expect(await storedCaptureKeys()).toHaveLength(0);
});

test('discarded and expired captures are removed from storage.session; at most 4 are kept', async () => {
  await openArticle();
  await chordAround(page.locator('#p3'));
  await expect(page.locator('#synapse-confirm-bar')).toBeVisible();
  expect(await storedCaptureKeys()).toHaveLength(1);
  await page.keyboard.press('Escape');
  await expect.poll(storedCaptureKeys).toHaveLength(0);

  // Cap + expiry, exercised directly against the store.
  const result = await worker().evaluate(async () => {
    const fake = { base64: 'AAAA', mediaType: 'image/webp', thumbBase64: null, thumbDataUrl: null };
    const ids = [];
    for (let i = 0; i < 6; i++) ids.push(await storeCapture(fake, 999));
    const keysAfterCap = Object.keys(await chrome.storage.session.get(null)).filter((k) => k.startsWith('pendingCapture:'));
    const wrongTab = await takeCapture(ids[5], 1);           // another tab: refused (and dropped)
    const oldest = await takeCapture(ids[0], 999);           // evicted by the cap
    // Expire one: rewrite its record in storage and forget the memory copy.
    const key = 'pendingCapture:' + ids[4];
    const rec = (await chrome.storage.session.get(key))[key];
    await chrome.storage.session.set({ [key]: { ...rec, expiresAt: Date.now() - 1 } });
    pendingCaptures.delete(ids[4]);
    const expired = await takeCapture(ids[4], 999);
    const ok = await takeCapture(ids[3], 999);
    for (const id of ids) await dropCapture(id);
    const left = Object.keys(await chrome.storage.session.get(null)).filter((k) => k.startsWith('pendingCapture:'));
    return { capped: keysAfterCap.length, wrongTab, oldest, expired, ok: ok && ok.base64, left: left.length };
  });
  expect(result).toEqual({ capped: 4, wrongTab: null, oldest: null, expired: null, ok: 'AAAA', left: 0 });
});

test('confirm bar: R restarts tracing in the same mode and sends nothing', async () => {
  await openArticle();
  const before = requests.length;
  await fabAround(page.locator('#chart'));
  const bar = page.locator('#synapse-confirm-bar');
  await expect(bar).toBeVisible();
  await page.keyboard.press('r');
  await expect(bar).toHaveCount(0);
  await expect(page.locator('#synapse-circle-overlay')).toBeAttached();
  await expect(page.locator('#synapse-circle-tip')).toContainText('Click where you want to start');
  await page.keyboard.press('Escape');
  await expect(page.locator('#synapse-circle-overlay')).toHaveCount(0);
  await page.waitForTimeout(300);
  expect(requests.length).toBe(before);
});

test('confirm bar: Esc cancels, removes the outline and sends nothing', async () => {
  await openArticle();
  const before = requests.length;
  await chordAround(page.locator('#p3'));
  const bar = page.locator('#synapse-confirm-bar');
  await expect(bar).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(bar).toHaveCount(0);
  await expect(page.locator('#synapse-circle-outline')).toHaveCount(0);
  await page.waitForTimeout(300);
  expect(requests.length).toBe(before);
});

test('FAB click-to-trace: click, move, click, Confirm sends', async () => {
  await openArticle();
  const before = requests.length;
  await fabAround(page.locator('#chart'));
  await page.locator('#synapse-confirm-bar').getByRole('button', { name: /Confirm/ }).click();
  const req = await waitForRequests(before + 1);
  expect(req.kind).toBe('image');
  expect(req.image_base64.length).toBeGreaterThan(100);
});

test('IMAGE_LIMIT errors show friendly copy inline', async () => {
  await openArticle();
  explainQueue.push({ status: 429, body: { detail: { code: 'IMAGE_LIMIT', message: 'limit' } } });
  await chordAround(page.locator('#chart'), 8);
  await expect(page.locator('#synapse-confirm-bar')).toBeVisible();
  await page.keyboard.press('Enter');
  const panel = page.locator('#synapse-explain-panel');
  await expect(panel.locator('.sxp-error')).toContainText('upgrade');
});

test('highlight on a vague button sends element metadata, heading path and form', async () => {
  await page.goto(`${base}/settings.html`);
  await expect(page.locator('#synapse-fab')).toBeVisible();
  const before = requests.length;
  await selectAndExplain('#sync');
  const req = await waitForRequests(before + 1);
  const local = req.context.local;
  expect(local.heading_path).toEqual(['Settings', 'Connected accounts', 'Chase Checking']);
  expect(local.surrounding_text).toContain('Last synced 3 days ago');
  expect(local.element).toMatchObject({
    tag: 'button',
    role: 'button',
    name: 'Sync',
    title: 'Refresh transactions from your bank',
    container: 'toolbar: Account actions',
    href: null,
  });
  expect(local.element.form.heading).toBe('Chase Checking');
  expect(local.element.form.fields).toEqual(expect.arrayContaining(['Nickname', 'Account type']));
  expect(req.context.page.site_name).toBe('MoneyApp');
  expect(req.context.page.outline).toEqual(['Settings', 'Profile', 'Connected accounts', 'Chase Checking']);
});

test('sensitive-looking host sends local context only until turned on for that site', async () => {
  const sensitive = `http://mail.synapse.test:${port}`;
  await openArticle(sensitive);
  let before = requests.length;
  await page.locator('#p2').click({ clickCount: 3 });
  await page.locator('#synapse-bubble').click();
  let req = await waitForRequests(before + 1);
  expect(req.page_url).toBe(`${sensitive}/article.html`);
  expect(req.context.local.surrounding_text).toContain('Ribosomes');
  expect(req.context.page).toBeUndefined();
  expect(req.context_id).toBeNull();

  const panel = page.locator('#synapse-explain-panel');
  await expect(panel.locator('.sxp-site-note')).toContainText('Page context is off on this site');
  await expect(panel.locator('.sxp-ctx-used')).toContainText('off on this site');
  const siteSwitch = panel.locator('.sxp-ctx-site');
  await expect(siteSwitch).toHaveAttribute('aria-checked', 'false');
  await siteSwitch.click();
  await expect(siteSwitch).toHaveAttribute('aria-checked', 'true');
  const stored = await readStorage(worker(), 'explainContextSettings');
  expect(stored.explainContextSettings.siteOverrides['mail.synapse.test']).toBe(true);

  before = requests.length;
  await page.locator('#p3').click({ clickCount: 3 });
  await page.locator('#synapse-bubble').click();
  req = await waitForRequests(before + 1);
  expect(req.context.page.main_text).toContain('cell membrane');
  await setContextSettings({ usePageContext: true, siteOverrides: {} });
});

test('"Use page context" Off removes page context', async () => {
  await openArticle();
  await page.locator('#synapse-history-btn').click();
  const panel = page.locator('#synapse-explain-panel');
  const sw = panel.locator('.sxp-ctx-global');
  await expect(sw).toHaveAttribute('aria-checked', 'true');
  await sw.click();
  await expect(sw).toHaveAttribute('aria-checked', 'false');
  await expect.poll(async () => (await readStorage(worker(), 'explainContextSettings')).explainContextSettings?.usePageContext).toBe(false);

  const before = requests.length;
  await page.locator('#p3').click({ clickCount: 3 });
  await page.locator('#synapse-bubble').click();
  const req = await waitForRequests(before + 1);
  expect(req.context.local.surrounding_text).toContain('cell membrane');
  expect(req.context.page).toBeUndefined();
  await sw.click();
  await expect(sw).toHaveAttribute('aria-checked', 'true');
});

test('QUOTA_INSUFFICIENT_FOR_CONTEXT offers a local-only resend, once', async () => {
  await openArticle();
  explainQueue.push({ status: 429, body: { detail: { code: 'QUOTA_INSUFFICIENT_FOR_CONTEXT', message: 'not enough' } } });
  let before = requests.length;
  await page.locator('#p2').click({ clickCount: 3 });
  await page.locator('#synapse-bubble').click();
  const first = await waitForRequests(before + 1);
  expect(first.context.page).toBeTruthy();

  const panel = page.locator('#synapse-explain-panel');
  await expect(panel.locator('.sxp-error')).toContainText('counts as 4');
  const fallback = panel.getByRole('button', { name: 'Explain without page context' });
  await expect(fallback).toBeVisible();

  before = requests.length;
  await fallback.click();
  const resend = await waitForRequests(before + 1);
  expect(resend.kind).toBe('text');
  expect(resend.text).toBe(first.text);
  expect(resend.context.page).toBeUndefined();
  expect(resend.context.local.surrounding_text).toContain('Ribosomes');
  expect(resend.context_id).toBeNull();
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for text');
  await expect(panel.locator('.sxp-ctx-used')).toContainText('without page context');

  // A plain 429 on the local-only resend shows its message and no second fallback.
  explainQueue.push({ status: 429, body: { detail: { code: 'QUOTA_INSUFFICIENT_FOR_CONTEXT', message: 'x' } } });
  explainQueue.push({ status: 429, body: { detail: 'Daily limit reached. Try again tomorrow.' } });
  before = requests.length;
  await page.locator('#p3').click({ clickCount: 3 });
  await page.locator('#synapse-bubble').click();
  await waitForRequests(before + 1);
  await panel.getByRole('button', { name: 'Explain without page context' }).click();
  await waitForRequests(before + 2);
  await expect(panel.locator('.sxp-error')).toContainText('Daily limit reached');
  await expect(panel.locator('.sxp-action')).toHaveCount(0);
});

test('history: delete one entry and clear the site', async () => {
  await openArticle();
  await page.locator('#synapse-history-btn').click();
  const panel = page.locator('#synapse-explain-panel');
  const items = panel.locator('.sxp-item');
  const count = await items.count();
  expect(count).toBeGreaterThanOrEqual(2);
  await items.first().locator('.sxp-item-del').click();
  await expect(items).toHaveCount(count - 1);
  await panel.locator('.sxp-clear-wrap .sxp-link').click();
  await panel.locator('.sxp-link.s-confirm').click();
  await expect(items).toHaveCount(0);
  const stored = await readStorage(worker(), 'explainHistoryLocal');
  expect(stored.explainHistoryLocal.filter((e) => e.hostname === '127.0.0.1')).toHaveLength(0);
});

test('document page: FAB opens the two-option prompt; Escape closes it', async () => {
  await page.goto(`${base}/notes.txt`);
  const fab = page.locator('#synapse-fab');
  await expect(fab).toBeVisible();
  await fab.click();
  const menu = page.locator('#synapse-fab-menu');
  await expect(menu).toBeVisible();
  await expect(menu.getByRole('menuitem')).toHaveCount(2);
  await expect(menu).toContainText('Circle something');
  await expect(menu).toContainText('Read this document');
  await expect(menu.getByRole('menuitem').first()).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(menu).toHaveCount(0);
  await expect(fab).toBeFocused();

  await fab.click();
  await menu.getByRole('menuitem', { name: /Circle something/ }).click();
  await expect(page.locator('#synapse-circle-overlay')).toBeAttached();
  await page.keyboard.press('Escape');
  await expect(page.locator('#synapse-circle-overlay')).toHaveCount(0);
});

test('text document: uploads context once and reuses context_id', async () => {
  await page.goto(`${base}/notes.txt`);
  await expect(page.locator('#synapse-fab')).toBeVisible();
  const uploadsBefore = ctxUploads.length;
  let before = requests.length;
  await selectAndExplain('body > pre');
  let req = await waitForRequests(before + 1);
  expect(ctxUploads.length).toBe(uploadsBefore + 1);
  const upload = ctxUploads[ctxUploads.length - 1];
  expect(upload.media_type).toBe('text/plain');
  expect(upload.document_text).toContain('Line two of the notes');
  expect(upload.document_base64 ?? null).toBeNull();
  expect(upload.source_url).toBe(`${base}/notes.txt`);
  const firstId = `ctx-${ctxCounter}`;
  expect(req.context_id).toBe(firstId);
  expect(req.source).toBe('document');
  expect(req.context.page).toBeUndefined();
  expect(req.context.local.surrounding_text).toContain('Plain text notes');
  await expect(page.locator('#synapse-explain-panel .sxp-ctx-used')).toContainText('whole document');

  before = requests.length;
  await selectAndExplain('body > pre');
  req = await waitForRequests(before + 1);
  expect(ctxUploads.length).toBe(uploadsBefore + 1);
  expect(req.context_id).toBe(firstId);
});

test('CONTEXT_EXPIRED triggers exactly one re-upload and a retry', async () => {
  await page.goto(`${base}/notes.txt`);
  await expect(page.locator('#synapse-fab')).toBeVisible();
  const uploadsBefore = ctxUploads.length;
  explainQueue.push({ status: 400, body: { detail: { code: 'CONTEXT_EXPIRED', message: 'expired' } } });
  const before = requests.length;
  await selectAndExplain('body > pre');
  const retry = await waitForRequests(before + 2);
  expect(requests[before].context_id).toBe(`ctx-${ctxCounter - 1}`);
  expect(ctxUploads.length).toBe(uploadsBefore + 1);
  expect(retry.context_id).toBe(`ctx-${ctxCounter}`);
  await expect(page.locator('#synapse-explain-panel .sxp-result')).toContainText('Mock explanation for text');
  await page.waitForTimeout(400);
  expect(requests.length).toBe(before + 2);
});

test('highlight inside the document reader explains against the original document', async () => {
  await page.goto(`${base}/notes.txt`);
  await page.locator('#synapse-fab').click();
  await page.locator('#synapse-fab-menu').getByRole('menuitem', { name: /Read this document/ }).click();
  const rebuilt = page.locator('#synapse-reader-overlay #rebuilt');
  await expect(rebuilt).toBeVisible();
  const before = requests.length;
  await rebuilt.click({ clickCount: 3 });
  const bubble = page.locator('#synapse-bubble');
  await expect(bubble).toBeVisible();
  await bubble.click();
  const req = await waitForRequests(before + 1);
  expect(req.text).toContain('Rebuilt paragraph about plain notes');
  expect(req.page_url).toBe(`${base}/notes.txt`);
  expect(req.context_id).toMatch(/^ctx-/);
  expect(req.context.local.heading_path).toEqual(['Notes rebuilt']);
  expect(req.context.local.surrounding_text).toContain('Rebuilt paragraph');
  expect(req.context.page).toBeUndefined();
});

test('explain scripts load on an extension page without content.js', async () => {
  const ext = await context.newPage();
  const errors = [];
  ext.on('pageerror', (e) => errors.push(String(e)));
  await ext.goto(`chrome-extension://${extensionId}/popup.html`);
  for (const f of ['purify.min.js', 'lib/geometry.js', 'explain/host.js', 'explain/core.js', 'explain/context.js',
    'explain/panel.js', 'explain/highlight.js', 'explain/circle.js', 'explain/main.js']) {
    await ext.addScriptTag({ url: `chrome-extension://${extensionId}/${f}` });
  }
  const docUrl = `${base}/notes.txt`;
  await ext.evaluate((url) => {
    const root = document.createElement('div');
    root.id = 'doc-root';
    // popup.html has its own content; keep the test document in view.
    root.style.cssText = 'position:fixed;top:20px;left:20px;width:300px;background:#fff;padding:8px;z-index:1000';
    root.innerHTML = '<h1>Viewer heading</h1><p id="vp">Viewer paragraph about organelles in a document.</p>';
    document.body.appendChild(root);
    globalThis.SynapseExplain.init({ document: { url, mediaType: 'text/plain' }, contentRoot: root });
  }, docUrl);
  expect(await ext.evaluate(() => globalThis.SynapseExplain.state.hostname)).toBe('127.0.0.1');

  const before = requests.length;
  await ext.evaluate(() => {
    const r = document.createRange();
    r.selectNodeContents(document.getElementById('vp'));
    const s = window.getSelection();
    s.removeAllRanges();
    s.addRange(r);
    document.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
  });
  await expect(ext.locator('#synapse-bubble')).toBeVisible();
  await ext.locator('#synapse-bubble').click();
  const req = await waitForRequests(before + 1);
  expect(req.page_url).toBe(docUrl);
  expect(req.text).toContain('Viewer paragraph');
  expect(req.context_id).toMatch(/^ctx-/);
  expect(req.context.local.heading_path).toEqual(['Viewer heading']);
  await expect(ext.locator('#synapse-explain-panel .sxp-result')).toContainText('Mock explanation');
  expect(errors).toEqual([]);
  await ext.close();
});

// ── Synapse PDF viewer ───────────────────────────────────────────
const viewerErrors = [];

function viewerUrl(fileUrl) {
  return `chrome-extension://${extensionId}/viewer/viewer.html?file=${encodeURIComponent(fileUrl)}`;
}

async function openViewer(fileUrl) {
  const v = await context.newPage();
  v.on('pageerror', (e) => viewerErrors.push(String(e)));
  v.on('console', (m) => { if (m.type() === 'error') viewerErrors.push(m.text()); });
  await v.goto(viewerUrl(fileUrl));
  return v;
}

/** The text-layer span whose text contains `needle`. */
function textSpan(v, needle) {
  return v.locator('#viewer .textLayer span', { hasText: needle }).first();
}

async function selectSpanText(v, needle) {
  await v.evaluate((n) => {
    const span = Array.from(document.querySelectorAll('#viewer .textLayer span')).find((s) => s.textContent.includes(n));
    const r = document.createRange();
    r.selectNodeContents(span);
    const sel = window.getSelection();
    sel.removeAllRanges();
    sel.addRange(r);
    document.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
  }, needle);
}

test('viewer: renders pages with a text layer, marks the image-only page, warms PDF document context', async () => {
  const uploadsBefore = ctxUploads.length;
  const v = await openViewer(`${base}/paper.pdf`);
  await expect(v.locator('#viewer .vw-page')).toHaveCount(4);
  await expect(v.locator('#pageCount')).toHaveText('of 4');
  await expect(v.locator('#docTitle')).toHaveText('paper.pdf');
  await expect(v).toHaveTitle('paper.pdf – Synapse');
  await expect(v.locator('.vw-page[data-page-number="1"] canvas')).toBeAttached();
  await expect(textSpan(v, 'Photosynthesis converts light energy')).toBeAttached();
  // HiDPI-aware canvas: backing store matches CSS size x devicePixelRatio.
  const dims = await v.evaluate(() => {
    const c = document.querySelector('.vw-page[data-page-number="1"] canvas');
    return { w: c.width, css: c.getBoundingClientRect().width, dpr: devicePixelRatio };
  });
  expect(Math.abs(dims.w - Math.floor(dims.css * dims.dpr))).toBeLessThanOrEqual(2);
  // Page 4 is an image only: no text, marked, and the document note says so.
  await expect(v.locator('.vw-page[data-page-number="4"]')).toHaveClass(/s-no-text/);
  await expect(v.locator('.vw-page[data-page-number="4"]')).toHaveAttribute('aria-label', /no selectable text/);
  await expect(v.locator('#docNote')).toContainText('no selectable text');
  await expect(v.locator('#openOriginal')).toHaveAttribute('href', `${base}/paper.pdf`);

  // prepareDocument(): one upload, as a PDF, keyed by the original URL.
  await expect.poll(() => ctxUploads.length).toBe(uploadsBefore + 1);
  const up = ctxUploads[ctxUploads.length - 1];
  expect(up.media_type).toBe('application/pdf');
  expect(up.source_url).toBe(`${base}/paper.pdf`);
  expect(Buffer.from(up.document_base64, 'base64').subarray(0, 5).toString('latin1')).toBe('%PDF-');

  // Zoom keeps the text layer and the page in step.
  const zoomBefore = await v.locator('#zoomLevel').textContent();
  await v.locator('#zoomIn').click();
  await expect(v.locator('#zoomLevel')).not.toHaveText(zoomBefore);
  await expect(v.locator('#fitWidth')).toHaveAttribute('aria-pressed', 'false');
  const misfit = await v.evaluate(() => {
    const p = document.querySelector('.vw-page[data-page-number="1"]').getBoundingClientRect();
    const l = document.querySelector('.vw-page[data-page-number="1"] .textLayer').getBoundingClientRect();
    return Math.abs(p.width - l.width) + Math.abs(p.height - l.height);
  });
  expect(misfit).toBeLessThanOrEqual(2);
  // Page jump.
  await v.locator('#pageNumber').fill('3');
  await v.locator('#pageNumber').press('Enter');
  await expect.poll(() => v.evaluate(() => document.querySelector('.vw-page[data-page-number="3"]').getBoundingClientRect().top)).toBeLessThan(200);
  await v.close();
});

test('viewer: selecting text shows the bubble; explain sends the original PDF URL and a context_id; green restores on reload', async () => {
  const v = await openViewer(`${base}/paper.pdf`);
  await expect(textSpan(v, 'Chlorophyll absorbs')).toBeAttached();
  await expect.poll(() => v.evaluate(() => globalThis.SynapseExplain.state.documentContextReady)).toBe(true);
  const before = requests.length;
  await selectSpanText(v, 'Chlorophyll absorbs');
  const bubble = v.locator('#synapse-bubble');
  await expect(bubble).toBeVisible();
  await bubble.click();
  const req = await waitForRequests(before + 1);
  expect(req.kind).toBe('text');
  expect(req.text).toContain('Chlorophyll absorbs mostly blue and red light');
  expect(req.page_url).toBe(`${base}/paper.pdf`);
  expect(req.page_title).toBe('paper.pdf');
  expect(req.context_id).toBe(`ctx-${ctxCounter}`);
  expect(req.source).toBe('pdf');
  expect(req.context.page).toBeUndefined();
  expect(req.context.local.surrounding_text).toContain('Chlorophyll');
  expect(req.anchor.quote).toContain('Chlorophyll absorbs');
  await expect(v.locator('#synapse-explain-panel .sxp-result')).toContainText('Mock explanation for text');
  await expect(v.locator('#synapse-explain-panel .sxp-ctx-used')).toContainText('whole document');
  await expect.poll(() => v.evaluate(() => CSS.highlights.get('synapse-explained')?.size ?? 0)).toBe(1);
  await expect(v.locator('#panelBtn')).toHaveAttribute('aria-expanded', 'true');

  // History belongs to the original URL (hostname 127.0.0.1), not the viewer.
  const stored = await readStorage(worker(), 'explainHistoryLocal');
  const entry = stored.explainHistoryLocal.find((e) => e.url === `${base}/paper.pdf`);
  expect(entry).toBeTruthy();
  expect(entry.hostname).toBe('127.0.0.1');

  // Reload: the text layer renders lazily, then the saved quote is painted green again.
  await v.reload();
  await expect(textSpan(v, 'Chlorophyll absorbs')).toBeAttached();
  await expect.poll(() => v.evaluate(() => CSS.highlights.get('synapse-explained')?.size ?? 0)).toBe(1);
  // Clicking the green passage reopens it without an API call.
  const n = requests.length;
  const box = await textSpan(v, 'Chlorophyll absorbs').boundingBox();
  await v.mouse.click(box.x + 30, box.y + box.height / 2);
  await expect(v.locator('#synapse-explain-panel .sxp-result')).toContainText('Mock explanation for text');
  await v.waitForTimeout(300);
  expect(requests.length).toBe(n);

  // Alt+Shift+E explains a selection from the keyboard.
  await v.locator('#synapse-explain-panel .sxp-close').click();
  await selectSpanText(v, 'Calvin cycle');
  await v.keyboard.press('Alt+Shift+E');
  const req2 = await waitForRequests(n + 1);
  expect(req2.text).toContain('Calvin cycle');
  expect(req2.page_url).toBe(`${base}/paper.pdf`);
  await v.close();
});

test('viewer: Circle button -> confirm bar -> Enter sends one image request for the original PDF', async () => {
  const v = await openViewer(`${base}/paper.pdf`);
  const span = textSpan(v, 'Photosynthesis converts light energy');
  await expect(span).toBeAttached();
  await expect(v.locator('.vw-page[data-page-number="1"] canvas')).toBeAttached();
  const box = await span.boundingBox();
  const before = requests.length;
  await v.locator('#circleBtn').click();
  await expect(v.locator('#synapse-circle-overlay')).toBeAttached();
  const pad = 8;
  await v.mouse.click(box.x - pad, box.y - pad);
  await v.mouse.move(box.x + box.width + pad, box.y - pad, { steps: 6 });
  await v.mouse.move(box.x + box.width + pad, box.y + box.height + pad, { steps: 6 });
  await v.mouse.move(box.x - pad, box.y + box.height + pad, { steps: 6 });
  await v.mouse.click(box.x - pad, box.y);
  const bar = v.locator('#synapse-confirm-bar');
  await expect(bar).toBeVisible();
  // captureVisibleTab works on the extension page.
  await expect(bar.locator('.sxc-preview img')).toHaveAttribute('src', /^data:image\/(webp|jpeg);base64,/);
  await v.waitForTimeout(300);
  expect(requests.length).toBe(before);
  await v.keyboard.press('Enter');
  const req = await waitForRequests(before + 1);
  expect(req.kind).toBe('image');
  expect(req.image_base64.length).toBeGreaterThan(100);
  expect(req.text).toContain('Photosynthesis converts light energy');
  expect(req.page_url).toBe(`${base}/paper.pdf`);
  expect(req.context_id).toMatch(/^ctx-/);
  expect(req.source).toBe('pdf');
  await expect(v.locator('#synapse-explain-panel .sxp-result')).toContainText('Mock explanation for image');
  await v.waitForTimeout(400);
  expect(requests.length).toBe(before + 1);

  // Alt+S chord works too, and scrolling the document cancels a trace.
  await v.mouse.move(200, 300);
  await v.keyboard.down('Alt');
  await v.keyboard.down('KeyS');
  await expect(v.locator('#synapse-circle-overlay')).toBeAttached();
  await v.evaluate(() => window.scrollBy(0, 200));
  await expect(v.locator('#synapse-circle-overlay')).toHaveCount(0);
  await v.keyboard.up('KeyS');
  await v.keyboard.up('Alt');
  await v.close();
});

test('viewer: history entry returns to its source in the scrolled document', async () => {
  const v = await openViewer(`${base}/paper.pdf`);
  await expect(textSpan(v, 'Chlorophyll absorbs')).toBeAttached();
  await expect.poll(() => v.evaluate(() => CSS.highlights.get('synapse-explained')?.size ?? 0)).toBeGreaterThanOrEqual(1);
  await v.evaluate(() => globalThis.SynapseViewer.scrollToPage(4));
  await expect.poll(() => v.evaluate(() => window.scrollY)).toBeGreaterThan(1000);
  await v.locator('#panelBtn').click();
  // Match the highlight's own entry by its snippet: the circle entry from the
  // Circle-button test can also contain "Chlorophyll" when its trace catches the
  // next line, and clicking that one returns to a different spot.
  const item = v.locator('#synapse-explain-panel .sxp-item', {
    has: v.locator('.sxp-item-snippet', { hasText: /^\s*Chlorophyll/ }),
  }).first();
  await item.locator('.sxp-item-main').click();
  await expect.poll(async () => {
    const r = await textSpan(v, 'Chlorophyll absorbs').boundingBox();
    const vh = await v.evaluate(() => innerHeight);
    return r && r.y > 40 && r.y + r.height < vh;
  }, { timeout: 10_000 }).toBe(true);
  await v.close();
});

test('viewer: "Read with Synapse" opens the reader; highlighting inside it explains against the PDF', async () => {
  const v = await openViewer(`${base}/paper.pdf`);
  await expect(textSpan(v, 'Photosynthesis')).toBeAttached();
  await v.locator('#readBtn').click();
  await expect(v.locator('#readBtn')).toHaveAttribute('aria-pressed', 'true');
  const rebuilt = v.locator('#synapse-reader-overlay #rebuilt');
  await expect(rebuilt).toBeVisible();
  const before = requests.length;
  await rebuilt.click({ clickCount: 3 });
  await expect(v.locator('#synapse-bubble')).toBeVisible();
  await v.locator('#synapse-bubble').click();
  const req = await waitForRequests(before + 1);
  expect(req.text).toContain('Rebuilt paragraph about plain notes');
  expect(req.page_url).toBe(`${base}/paper.pdf`);
  expect(req.context_id).toMatch(/^ctx-/);
  expect(req.source).toBe('pdf');
  // Escape (focus inside the reader) closes it.
  await v.locator('.synapse-reader-close').focus();
  await v.keyboard.press('Escape');
  await expect(v.locator('#synapse-reader-overlay')).toHaveCount(0);
  await expect(v.locator('#readBtn')).toHaveAttribute('aria-pressed', 'false');
  await v.close();
});

test('viewer: password-protected PDF asks for the password inline', async () => {
  const v = await openViewer(`${base}/locked.pdf`);
  const form = v.locator('#passwordForm');
  await expect(form).toBeVisible();
  const input = v.getByLabel('Password', { exact: true });
  await expect(input).toBeFocused();
  await input.fill('wrong');
  await input.press('Enter');
  await expect(v.locator('#passwordError')).toContainText('not right');
  await expect(input).toHaveAttribute('aria-invalid', 'true');
  await input.fill('synapse');
  await v.getByRole('button', { name: 'Open PDF' }).click();
  await expect(form).toBeHidden();
  await expect(textSpan(v, 'This secret page explains enzymes')).toBeAttached();
  await v.close();
});

test('viewer: load errors show a clear message and Open original', async () => {
  let v = await openViewer(`${base}/missing.pdf`);
  await expect(v.locator('#errorBox')).toBeVisible();
  await expect(v.locator('#errorTitle')).toHaveText("Couldn't download this PDF");
  await expect(v.locator('#errorText')).toContainText('404');
  await expect(v.locator('#errorOpenOriginal')).toHaveAttribute('href', `${base}/missing.pdf`);
  await v.close();

  v = await openViewer(`${base}/broken.pdf`);
  await expect(v.locator('#errorTitle')).toHaveText("This file isn't a readable PDF");
  await v.close();

  // Local PDF without Chrome's 'Allow access to file URLs' (off by default for unpacked extensions).
  // The test profile loads the extension unpacked, which grants file access: local PDFs render.
  const localPdf = pathToFileURL(path.join(FIXTURES, 'sample.pdf')).href;
  v = await openViewer(localPdf);
  await expect(textSpan(v, 'Photosynthesis converts light energy')).toBeAttached();
  await expect(v.locator('#readBtn')).toBeEnabled();
  await v.close();
  // Without the permission (simulated), the viewer explains how to turn it on.
  v = await context.newPage();
  await v.addInitScript(() => {
    chrome.extension.isAllowedFileSchemeAccess = (cb) => cb(false);
  });
  await v.goto(viewerUrl(localPdf));
  await expect(v.locator('#errorBox')).toBeVisible();
  await expect(v.locator('#errorTitle')).toHaveText('Synapse needs access to local files');
  await expect(v.locator('#fileAccessSteps')).toBeVisible();
  await expect(v.locator('#fileAccessSteps')).toContainText('Allow access to file URLs');
  await expect(v.getByRole('button', { name: 'Open Synapse settings' })).toBeFocused();
  await expect(v.locator('#readBtn')).toBeDisabled();
  await v.close();

  v = await context.newPage();
  await v.goto(`chrome-extension://${extensionId}/viewer/viewer.html?file=${encodeURIComponent('javascript:alert(1)')}`);
  await expect(v.locator('#errorTitle')).toHaveText("Synapse can't open this address");
  await v.close();
});

test('PDF page: FAB prompt offers three options; "Open in Synapse viewer" navigates to the viewer', async () => {
  await page.bringToFront();
  await page.goto(`${base}/paper.pdf`);
  const fab = page.locator('#synapse-fab');
  await expect(fab).toBeVisible();
  await fab.click();
  const menu = page.locator('#synapse-fab-menu');
  await expect(menu.getByRole('menuitem')).toHaveCount(3);
  await expect(menu.getByRole('menuitem').nth(0)).toContainText('Open in Synapse viewer');
  await expect(menu.getByRole('menuitem').nth(1)).toContainText('Circle something');
  await expect(menu.getByRole('menuitem').nth(2)).toContainText('Read this document');
  // (No focus assertion here: Chrome's PDF plugin keeps keyboard focus on PDF tabs.
  // Menu focus handling is covered by the text-document prompt test.)
  await menu.getByRole('menuitem', { name: /Open in Synapse viewer/ }).click();
  await page.waitForURL(viewerUrl(`${base}/paper.pdf`));
  await expect(textSpan(page, 'Photosynthesis converts light energy')).toBeAttached();
});

test('local text file (file://): FAB prompt; explain and the reader get the file text from the page', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'synapse-local-'));
  const file = path.join(dir, 'local-notes.txt');
  fs.writeFileSync(file, NOTES);
  const fileUrl = pathToFileURL(file).href;
  await page.bringToFront();
  await page.goto(fileUrl);
  const fab = page.locator('#synapse-fab');
  await expect(fab).toBeVisible();
  await fab.click();
  const menu = page.locator('#synapse-fab-menu');
  await expect(menu.getByRole('menuitem')).toHaveCount(2);
  await page.keyboard.press('Escape');

  // The worker can't read file://, so the page hands over the text.
  const uploadsBefore = ctxUploads.length;
  const before = requests.length;
  await selectAndExplain('body > pre');
  const req = await waitForRequests(before + 1);
  expect(ctxUploads.length).toBe(uploadsBefore + 1);
  const up = ctxUploads[ctxUploads.length - 1];
  expect(up.source_url).toBe(fileUrl);
  expect(up.document_text).toContain('Line two of the notes');
  expect(req.context_id).toBe(`ctx-${ctxCounter}`);
  expect(req.page_url).toBe(fileUrl);

  const readsBefore = docReads.length;
  await fab.click();
  await menu.getByRole('menuitem', { name: /Read this document/ }).click();
  await expect(page.locator('#synapse-reader-overlay #rebuilt')).toBeVisible();
  expect(docReads.length).toBe(readsBefore + 1);
  expect(Buffer.from(docReads[docReads.length - 1].base64_data, 'base64').toString('utf8')).toContain('Line two of the notes');

  // History works like any other site: local files share the "local-files" site.
  const stored = await readStorage(worker(), 'explainHistoryLocal');
  const entry = stored.explainHistoryLocal.find((e) => e.url === fileUrl);
  expect(entry?.hostname).toBe('local-files');

  // From another local file, the entry is listed and opens its source.
  const other = path.join(dir, 'other.txt');
  fs.writeFileSync(other, 'Another local file.\n');
  await page.goto(pathToFileURL(other).href);
  const historyBtn = page.locator('#synapse-history-btn');
  await expect(historyBtn).toHaveClass(/s-has-history/);
  await historyBtn.click();
  const item = page.locator(`#synapse-explain-panel .sxp-item[data-id="${entry.id}"] .sxp-item-main`);
  await expect(item).toBeVisible();
  await item.click();
  await page.waitForURL(fileUrl);
  // Back on the source: the green highlight is restored.
  await expect.poll(() => page.evaluate(() => CSS.highlights.get('synapse-explained')?.size ?? 0)).toBeGreaterThan(0);
  fs.rmSync(dir, { recursive: true, force: true });
});

test('local PDF (file://): FAB prompt; "Read this document" opens the viewer and reads the bytes it loaded', async () => {
  const localPdf = pathToFileURL(path.join(FIXTURES, 'sample.pdf')).href;
  await page.bringToFront();
  await page.goto(localPdf);
  const fab = page.locator('#synapse-fab');
  await expect(fab).toBeVisible();
  await fab.click();
  const menu = page.locator('#synapse-fab-menu');
  await expect(menu.getByRole('menuitem')).toHaveCount(3);
  const uploadsBefore = ctxUploads.length;
  const readsBefore = docReads.length;
  await menu.getByRole('menuitem', { name: /Read this document/ }).click();
  await page.waitForURL((u) => u.href.startsWith(`chrome-extension://${extensionId}/viewer/viewer.html`));
  await expect(page.locator('#synapse-reader-overlay #rebuilt')).toBeVisible();
  // read=1 is one-shot: dropped from the URL once the reader opens.
  expect(page.url()).toBe(viewerUrl(localPdf));
  expect(docReads.length).toBe(readsBefore + 1);
  expect(Buffer.from(docReads[docReads.length - 1].base64_data, 'base64').subarray(0, 5).toString('latin1')).toBe('%PDF-');
  // Document context came from bytes the viewer loaded (uploaded once per
  // document and cached, so possibly by the earlier viewer test).
  expect(ctxUploads.length).toBeLessThanOrEqual(uploadsBefore + 1);
  const up = ctxUploads.find((u) => u.source_url === localPdf);
  expect(up).toBeTruthy();
  expect(Buffer.from(up.document_base64, 'base64').subarray(0, 5).toString('latin1')).toBe('%PDF-');
});

// Last of the request-sending tests: they add explain requests, and the
// tests above count requests by absolute index.
test('"Clearer": one rating per explanation, kept after reopening; anonymous explains carry it', async () => {
  await openArticle();
  await writeStorage(worker(), { feedbackLog: [], explainFeedbackGiven: [] });
  await setContextSettings({ usePageContext: true, siteOverrides: {} });

  const panel = page.locator('#synapse-explain-panel');
  const before = requests.length;
  await selectAndExplain('#p2');
  await waitForRequests(before + 1);
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for text');

  // "Too complex", "Too simple" and "Missed the point" are gone: re-explain replaced them.
  await expect(panel.locator('.sc-feedback')).toHaveCount(0);
  await expect(panel.getByRole('button', { name: /Missed the point|Too complex|Too simple/ })).toHaveCount(0);

  await panel.locator('.sxp-clearer').click();
  await expect(panel.locator('.sxp-thanks')).toBeVisible();
  await expect(panel.locator('.sxp-clearer')).toHaveCount(0);

  await expect.poll(async () => (await readStorage(worker(), 'feedbackLog')).feedbackLog.length).toBe(1);
  const { feedbackLog } = await readStorage(worker(), 'feedbackLog');
  expect(feedbackLog[0]).toMatchObject({
    reaction: 'clearer', sectionTitle: 'Explain', readProgress: null, reexplainPath: [], synced: false,
  });

  // Reopening the same entry (green highlight, no API call) offers no second rating.
  await panel.locator('.sxp-close').click();
  await expect(panel).not.toHaveClass(/s-visible/);
  const reopenBefore = requests.length;
  const box = await page.locator('#p2').boundingBox();
  await page.mouse.click(box.x + 40, box.y + 12);
  await expect(panel).toHaveClass(/s-visible/);
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for text');
  await expect(panel.locator('.sxp-clearer')).toHaveCount(0);
  await expect(panel.locator('.sxp-thanks')).toBeVisible();
  expect(requests.length).toBe(reopenBefore);

  // Signed out, the next explain carries the local log so it can still adapt.
  await page.reload();
  await expect(page.locator('#synapse-fab')).toBeVisible();
  await selectAndExplain('#p3');
  const req = await waitForRequests(reopenBefore + 1);
  expect(req.recent_feedback).toEqual([
    expect.objectContaining({ reaction: 'clearer', read_progress: null, section_title: 'Explain', reexplain_path: null }),
  ]);
  expect(req.profile).toBeTruthy();
});

test('re-explain: Simpler then a specific request stack as versions of one entry; only "Clearer" is logged', async () => {
  await openArticle();
  await writeStorage(worker(), { feedbackLog: [], explainFeedbackGiven: [] });
  const panel = page.locator('#synapse-explain-panel');
  const historyBefore = (await readStorage(worker(), 'explainHistoryLocal')).explainHistoryLocal.length;

  const before = requests.length;
  await selectAndExplain('#p1');
  const first = await waitForRequests(before + 1);
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for text');
  await expect(panel.locator('.sxp-versions')).toBeHidden();

  // Simpler: same source and context, the version on screen, no history parent (local entry).
  await panel.getByRole('button', { name: 'Simpler' }).click();
  const simpler = await waitForRequests(before + 2);
  expect(simpler.reexplain).toEqual({
    mode: 'simpler', request: null,
    previous_html: expect.stringContaining('Mock explanation for text'),
    parent_entry_id: null,
  });
  expect(simpler.text).toBe(first.text);
  expect(simpler.context).toEqual(first.context);
  expect(simpler.thumbnail_base64).toBeNull();
  await expect(panel.locator('.sxp-result')).toContainText('Mock simpler version for text');
  await expect(panel.locator('.sxp-ver')).toHaveText(['Original', '2 · Simpler']);
  await expect(panel.locator('.sxp-ver[aria-pressed="true"]')).toHaveText('2 · Simpler');
  await expect(panel.locator('.sxp-note')).toContainText('free re-explains left today');

  // A specific request, relative to the simpler version now on screen.
  await panel.getByRole('button', { name: 'Ask something specific' }).click();
  const input = panel.locator('.sxp-ask-input');
  await expect(input).toBeFocused();
  await input.fill('Use a cooking analogy');
  await input.press('Enter');
  const specific = await waitForRequests(before + 3);
  expect(specific.reexplain).toMatchObject({
    mode: 'specific', request: 'Use a cooking analogy',
    previous_html: expect.stringContaining('Mock simpler version'),
  });
  await expect(panel.locator('.sxp-ver')).toHaveText(['Original', '2 · Simpler', '3 · Your request']);
  await expect(panel.locator('.sxp-result')).toContainText('Mock specific version');

  // Flip back to the original without a request.
  await panel.locator('.sxp-ver', { hasText: 'Original' }).click();
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for text');
  expect(requests.length).toBe(before + 3);

  // One entry with two extra versions, not three entries; the list says so.
  const { explainHistoryLocal } = await readStorage(worker(), 'explainHistoryLocal');
  expect(explainHistoryLocal.length).toBe(Math.min(10, historyBefore + 1));
  const entry = explainHistoryLocal.find((e) => (e.versions || []).length);
  expect(entry.versions.map((v) => [v.mode, v.request])).toEqual([['simpler', null], ['specific', 'Use a cooking analogy']]);
  await expect(panel.locator('.sxp-item-meta').first()).toContainText('3 versions');

  // Re-explains are not feedback. "Clearer" on version 3 records how it got there.
  expect((await readStorage(worker(), 'feedbackLog')).feedbackLog).toEqual([]);
  await panel.locator('.sxp-ver', { hasText: '3 · Your request' }).click();
  await panel.locator('.sxp-clearer').click();
  await expect.poll(async () => (await readStorage(worker(), 'feedbackLog')).feedbackLog.length).toBe(1);
  const { feedbackLog } = await readStorage(worker(), 'feedbackLog');
  expect(feedbackLog[0]).toMatchObject({ reaction: 'clearer', reexplainPath: ['simpler', 'specific'] });

  // When the free allowance is spent, the note says the re-explain was charged.
  explainQueue.push({
    status: 200,
    body: {
      html: '<p>Paid version</p>', kind: 'text', model_used: 'mock', history_entry: null, usage: null,
      reexplain: { free: false, free_remaining: 0, free_limit: 10 },
    },
  });
  await panel.getByRole('button', { name: 'More detail' }).click();
  await waitForRequests(before + 4);
  await expect(panel.locator('.sxp-note')).toContainText('counted as a normal explain');
});

test('re-explain a circle: re-looks at the crop kept for an hour; after that it says so', async () => {
  await openArticle();
  const panel = page.locator('#synapse-explain-panel');
  const before = requests.length;
  await fabAround(page.locator('#chart'));
  await page.locator('#synapse-confirm-bar').getByRole('button', { name: /Confirm/ }).click();
  const original = await waitForRequests(before + 1);
  await expect(panel.locator('.sxp-result')).toContainText('Mock explanation for image');

  // The crop is kept in session storage under the entry, for an hour.
  const relook = await worker().evaluate(async () => {
    const all = await chrome.storage.session.get(null);
    return Object.entries(all).filter(([k]) => k.startsWith('relookCrop:')).map(([k, v]) => ({ k, ttl: v.expiresAt - v.createdAt }));
  });
  expect(relook.length).toBeGreaterThanOrEqual(1);
  expect(relook[relook.length - 1].ttl).toBe(60 * 60 * 1000);

  await panel.getByRole('button', { name: 'More detail' }).click();
  const again = await waitForRequests(before + 2);
  expect(again.kind).toBe('image');
  expect(again.image_base64).toBe(original.image_base64); // the same crop, no new screenshot
  expect(again.thumbnail_base64).toBeNull();
  expect(again.reexplain.mode).toBe('more_detail');
  await expect(panel.locator('.sxp-result')).toContainText('Mock more_detail version for image');

  // Past the hour, the crop is gone. The chart has no text to fall back on,
  // so the panel explains why instead of sending anything.
  await worker().evaluate(async () => {
    const all = await chrome.storage.session.get(null);
    const expired = {};
    for (const [k, v] of Object.entries(all)) if (k.startsWith('relookCrop:')) expired[k] = { ...v, expiresAt: Date.now() - 1 };
    await chrome.storage.session.set(expired);
  });
  // The worker's in-memory copy goes when the worker restarts.
  await stopServiceWorker();
  await page.bringToFront();
  await panel.getByRole('button', { name: 'Simpler' }).click();
  await expect(panel.locator('.sxp-note.s-error')).toContainText('only kept for an hour');
  expect(requests.length).toBe(before + 2);
});

test('viewer: no page errors', async () => {
  const ours = viewerErrors.filter((t) => !/Failed to load resource|favicon/i.test(t));
  expect(ours).toEqual([]);
});

test('no console errors from the extension during the run', async () => {
  // The 4xx tests log the browser's own network line for the mock API; ignore resource-load noise.
  const ours = consoleErrors.filter((t) => !/Failed to load resource|favicon/i.test(t));
  expect(ours).toEqual([]);
});
